import { Difficulty, DietType, Unit } from '@prisma/client';

// Type definitions for recipe creation
type IngredientInput = {
    name: string;
    quantity: number;
    unit: Unit;
    optional?: boolean;                                                                                                                                                              
};

type RecipeInput = {
    title: string;
    slug: string;
    description: string;
    prepTime: number;
    cookTime: number;
    difficulty: Difficulty;
    servings?: number;
    isAdaptable?: boolean;
    tags: string[];
    toolsRequired: string[];
    dietTypes: DietType[];
    ingredients: IngredientInput[];
    steps: Array<{ stepNumber: number; instruction: string }>;
    calories?: number;
    carbohydrates?: number;
    fats?: number;
    proteins?: number;
    fibers?: number;
};

// Even MORE recipes collection!
export const moreRecipes: RecipeInput[] = [
    // === RECETTES ASIATIQUES ===
    {
        title: 'Pad Thaï aux Légumes',
        slug: 'pad-thai-legumes',
        description: 'Pad thaï végétarien aux légumes croquants et nouilles de riz',
        prepTime: 20,
        cookTime: 15,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['vegetarian', 'asian', 'spicy'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'nouilles de riz', quantity: 300, unit: Unit.G },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'chou', quantity: 200, unit: Unit.G },
            { name: 'poivron', quantity: 2, unit: Unit.PIECE },
            { name: 'pousses de soja', quantity: 150, unit: Unit.G },
            { name: 'cacahuète', quantity: 50, unit: Unit.G },
            { name: 'sauce soja', quantity: 3, unit: Unit.TBSP },
            { name: 'citron', quantity: 2, unit: Unit.PIECE },
            { name: 'sucre', quantity: 2, unit: Unit.TBSP },
            { name: 'huile végétale', quantity: 3, unit: Unit.TBSP },
            { name: 'ciboulette', quantity: 0.5, unit: Unit.BUNCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Tremper les nouilles dans l\'eau chaude 10 minutes.' },
            { stepNumber: 2, instruction: 'Couper les légumes en julienne.' },
            { stepNumber: 3, instruction: 'Faire sauter les légumes dans l\'huile 5 minutes.' },
            { stepNumber: 4, instruction: 'Ajouter les nouilles égouttées, la sauce soja et le sucre.' },
            { stepNumber: 5, instruction: 'Servir avec les cacahuètes concassées, la ciboulette et le citron.' },
        ],
    },
    {
        title: 'Nouilles Sautées au Bœuf',
        slug: 'nouilles-sautees-boeuf',
        description: 'Nouilles chinoises sautées au bœuf et aux légumes',
        prepTime: 15,
        cookTime: 15,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['quick', 'asian'],
        toolsRequired: ['casserole'],
        dietTypes: [],        ingredients: [
            { name: 'nouilles soba', quantity: 400, unit: Unit.G },
            { name: 'boeuf haché', quantity: 500, unit: Unit.G },
            { name: 'chou', quantity: 200, unit: Unit.G },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'gingembre', quantity: 20, unit: Unit.G },
            { name: 'sauce soja', quantity: 4, unit: Unit.TBSP },
            { name: 'huile de sésame', quantity: 1, unit: Unit.TSP },
            { name: 'huile végétale', quantity: 3, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire les nouilles selon les instructions.' },
            { stepNumber: 2, instruction: 'Faire revenir le bœuf dans l\'huile jusqu\'à cuisson, réserver.' },
            { stepNumber: 3, instruction: 'Faire sauter les légumes avec l\'ail et le gingembre 5 minutes.' },
            { stepNumber: 4, instruction: 'Ajouter les nouilles, le bœuf, la sauce soja et l\'huile de sésame.' },
            { stepNumber: 5, instruction: 'Faire sauter 3 minutes et servir chaud.' },
        ],
    },
    {
        title: 'Curry Vert au Poulet',
        slug: 'curry-vert-poulet',
        description: 'Curry vert thaïlandais au poulet et lait de coco',
        prepTime: 20,
        cookTime: 25,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['asian', 'spicy'],
        toolsRequired: ['casserole'],
        dietTypes: [],        ingredients: [
            { name: 'poulet', quantity: 800, unit: Unit.G },
            { name: 'lait de coco', quantity: 400, unit: Unit.ML },
            { name: 'pâte de curry', quantity: 3, unit: Unit.TBSP },
            { name: 'aubergine', quantity: 1, unit: Unit.PIECE },
            { name: 'basilic', quantity: 1, unit: Unit.BUNCH },
            { name: 'citron vert', quantity: 2, unit: Unit.PIECE },
            { name: 'nuoc mam', quantity: 2, unit: Unit.TBSP },
            { name: 'sucre', quantity: 1, unit: Unit.TBSP },
            { name: 'huile végétale', quantity: 2, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper le poulet en morceaux et faire revenir dans l\'huile.' },
            { stepNumber: 2, instruction: 'Ajouter la pâte de curry vert et faire revenir 2 minutes.' },
            { stepNumber: 3, instruction: 'Verser le lait de coco et laisser mijoter 15 minutes.' },
            { stepNumber: 4, instruction: 'Ajouter l\'aubergine et cuire 8 minutes de plus.' },
            { stepNumber: 5, instruction: 'Ajouter la sauce poisson, le sucre et le basilic. Servir avec du riz et du citron vert.' },
        ],
    },
    {
        title: 'Sushi Maison',
        slug: 'sushi-maison',
        description: 'Sushi aux légumes et poisson, version maison',
        prepTime: 45,
        cookTime: 20,
        difficulty: Difficulty.HARD,
        servings: 4,
        tags: ['japanese', 'fish'],
        toolsRequired: [],
        dietTypes: [DietType.PESCATARIAN],        ingredients: [
            { name: 'riz', quantity: 300, unit: Unit.G },
            { name: 'vinaigre de riz', quantity: 3, unit: Unit.TBSP },
            { name: 'sucre', quantity: 2, unit: Unit.TSP },
            { name: 'saumon', quantity: 200, unit: Unit.G },
            { name: 'concombre', quantity: 1, unit: Unit.PIECE },
            { name: 'avocat', quantity: 1, unit: Unit.PIECE },
            { name: 'algue nori', quantity: 8, unit: Unit.PIECE },
            { name: 'wasabi', quantity: 2, unit: Unit.TSP },
            { name: 'gingembre confit', quantity: 30, unit: Unit.G },
            { name: 'sauce soja', quantity: 4, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire le riz et le laisser refroidir légèrement.' },
            { stepNumber: 2, instruction: 'Mélanger le vinaigre de riz avec le sucre et l\'incorporer au riz.' },
            { stepNumber: 3, instruction: 'Couper le saumon, le concombre et l\'avocat en bâtonnets.' },
            { stepNumber: 4, instruction: 'Étaler le riz sur les algues nori, ajouter les légumes et le poisson, rouler.' },
            { stepNumber: 5, instruction: 'Couper en rondelles et servir avec le wasabi, le gingembre et la sauce soja.' },
        ],
    },

    // === RECETTES MEXICAINES ===
    {
        title: 'Tacos au Poulet',
        slug: 'tacos-poulet',
        description: 'Tacos mexicains au poulet épicé et légumes frais',
        prepTime: 20,
        cookTime: 15,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['mexican', 'quick', 'spicy'],
        toolsRequired: ['casserole'],
        dietTypes: [],        ingredients: [
            { name: 'poulet', quantity: 600, unit: Unit.G },
            { name: 'tortillas', quantity: 8, unit: Unit.PIECE },
            { name: 'tomate', quantity: 3, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'salade', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'citron vert', quantity: 2, unit: Unit.PIECE },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'paprika', quantity: 1, unit: Unit.TSP },
            { name: 'coriandre', quantity: 1, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire mariner le poulet avec les épices et le citron vert 15 minutes.' },
            { stepNumber: 2, instruction: 'Faire cuire le poulet dans l\'huile 12 minutes jusqu\'à doré.' },
            { stepNumber: 3, instruction: 'Couper les légumes en dés fins.' },
            { stepNumber: 4, instruction: 'Chauffer les tortillas 30 secondes de chaque côté.' },
            { stepNumber: 5, instruction: 'Garnir les tortillas avec le poulet, les légumes et la coriandre.' },
        ],
    },
    {
        title: 'Enchiladas au Fromage',
        slug: 'enchiladas-fromage',
        description: 'Enchiladas végétariennes au fromage et sauce tomate',
        prepTime: 25,
        cookTime: 30,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['mexican', 'vegetarian'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'tortillas', quantity: 12, unit: Unit.PIECE },
            { name: 'fromage râpé', quantity: 300, unit: Unit.G },
            { name: 'tomate concassée', quantity: 800, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'paprika', quantity: 1, unit: Unit.TSP },
            { name: 'coriandre', quantity: 1, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir l\'oignon et l\'ail, ajouter les tomates et épices, mijoter 15 minutes.' },
            { stepNumber: 2, instruction: 'Préchauffer le four à 180°C.' },
            { stepNumber: 3, instruction: 'Garnir chaque tortilla de fromage et rouler.' },
            { stepNumber: 4, instruction: 'Disposer dans un plat, recouvrir de sauce tomate et de fromage.' },
            { stepNumber: 5, instruction: 'Enfourner 25 minutes jusqu\'à gratiné. Parsemer de coriandre.' },
        ],
    },
    {
        title: 'Burritos aux Haricots',
        slug: 'burritos-haricots',
        description: 'Burritos végétariens aux haricots noirs et légumes',
        prepTime: 15,
        cookTime: 20,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['mexican', 'vegetarian', 'quick'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'tortillas', quantity: 4, unit: Unit.PIECE },
            { name: 'haricots noirs', quantity: 400, unit: Unit.G },
            { name: 'riz', quantity: 200, unit: Unit.G },
            { name: 'tomate', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'avocat', quantity: 1, unit: Unit.PIECE },
            { name: 'citron vert', quantity: 1, unit: Unit.PIECE },
            { name: 'coriandre', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire le riz et réchauffer les haricots.' },
            { stepNumber: 2, instruction: 'Couper les légumes en dés, écraser l\'avocat avec le citron vert.' },
            { stepNumber: 3, instruction: 'Assaisonner les haricots avec le cumin.' },
            { stepNumber: 4, instruction: 'Chauffer les tortillas et garnir avec riz, haricots, légumes et avocat.' },
            { stepNumber: 5, instruction: 'Rouler les burritos et servir.' },
        ],
    },

    // === RECETTES DU MONDE ===
    {
        title: 'Couscous Royal',
        slug: 'couscous-royal',
        description: 'Couscous avec agneau, poulet, merguez et légumes',
        prepTime: 30,
        cookTime: 90,
        difficulty: Difficulty.HARD,
        servings: 6,
        tags: ['moroccan', 'comfort_food'],
        toolsRequired: ['casserole'],
        dietTypes: [],        ingredients: [
            { name: 'agneau haché', quantity: 600, unit: Unit.G },
            { name: 'poulet', quantity: 600, unit: Unit.G },
            { name: 'merguez', quantity: 8, unit: Unit.PIECE },
            { name: 'semoule', quantity: 500, unit: Unit.G },
            { name: 'carotte', quantity: 4, unit: Unit.PIECE },
            { name: 'courgette', quantity: 2, unit: Unit.PIECE },
            { name: 'navet', quantity: 4, unit: Unit.PIECE },
            { name: 'pois chiches', quantity: 400, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate concassée', quantity: 400, unit: Unit.G },
            { name: 'gingembre', quantity: 20, unit: Unit.G },
            { name: 'coriandre', quantity: 1, unit: Unit.BUNCH },
            { name: 'bouillon', quantity: 1500, unit: Unit.ML },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir les morceaux d\'agneau et de poulet dans une grande casserole.' },
            { stepNumber: 2, instruction: 'Ajouter les oignons, le gingembre, les tomates et le bouillon.' },
            { stepNumber: 3, instruction: 'Laisser mijoter 1h, ajouter les légumes et les pois chiches.' },
            { stepNumber: 4, instruction: 'Cuire la semoule selon les instructions.' },
            { stepNumber: 5, instruction: 'Faire griller les merguez. Servir la viande et les légumes sur la semoule avec le bouillon.' },
        ],
    },
    {
        title: 'Paella Valencienne',
        slug: 'paella-valencienne',
        description: 'Paella traditionnelle aux fruits de mer et poulet',
        prepTime: 30,
        cookTime: 45,
        difficulty: Difficulty.HARD,
        servings: 6,
        tags: ['spanish', 'seafood'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.PESCATARIAN],        ingredients: [
            { name: 'riz', quantity: 450, unit: Unit.G },
            { name: 'poulet', quantity: 600, unit: Unit.G },
            { name: 'crevettes', quantity: 300, unit: Unit.G },
            { name: 'moules', quantity: 500, unit: Unit.G },
            { name: 'poivron', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'safran', quantity: 0.5, unit: Unit.TSP },
            { name: 'bouillon de poulet', quantity: 1200, unit: Unit.ML },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'citron', quantity: 2, unit: Unit.PIECE },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir le poulet coupé en morceaux dans l\'huile, réserver.' },
            { stepNumber: 2, instruction: 'Faire revenir les légumes dans la même poêle, ajouter le safran.' },
            { stepNumber: 3, instruction: 'Ajouter le riz, faire nacrer, verser le bouillon et remettre le poulet.' },
            { stepNumber: 4, instruction: 'Laisser cuire 20 minutes, ajouter les fruits de mer et cuire 10 minutes de plus.' },
            { stepNumber: 5, instruction: 'Laisser reposer 5 minutes. Servir avec des quartiers de citron.' },
        ],
    },
    {
        title: 'Moussaka Grecque',
        slug: 'moussaka-grecque',
        description: 'Moussaka aux aubergines, viande et béchamel',
        prepTime: 45,
        cookTime: 60,
        difficulty: Difficulty.HARD,
        servings: 6,
        tags: ['greek', 'comfort_food'],
        toolsRequired: ['oven'],
        dietTypes: [],        ingredients: [
            { name: 'aubergine', quantity: 4, unit: Unit.PIECE },
            { name: 'boeuf haché', quantity: 600, unit: Unit.G },
            { name: 'tomate concassée', quantity: 400, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'beurre', quantity: 60, unit: Unit.G },
            { name: 'farine', quantity: 60, unit: Unit.G },
            { name: 'lait', quantity: 500, unit: Unit.ML },
            { name: 'fromage râpé', quantity: 150, unit: Unit.G },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'cannelle', quantity: 0.5, unit: Unit.TSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper les aubergines en rondelles et les faire griller au four.' },
            { stepNumber: 2, instruction: 'Faire revenir la viande avec oignon et ail, ajouter les tomates et la cannelle, mijoter 30 minutes.' },
            { stepNumber: 3, instruction: 'Faire la béchamel : beurre, farine, lait en fouettant.' },
            { stepNumber: 4, instruction: 'Dans un plat, alterner couches d\'aubergines et de viande.' },
            { stepNumber: 5, instruction: 'Recouvrir de béchamel et fromage. Cuire au four 40 minutes à 180°C.' },
        ],
    },
    {
        title: 'Biryani au Poulet',
        slug: 'biryani-poulet',
        description: 'Riz biryani épicé au poulet, spécialité indienne',
        prepTime: 45,
        cookTime: 60,
        difficulty: Difficulty.HARD,
        servings: 6,
        tags: ['indian', 'spicy'],
        toolsRequired: ['oven'],
        dietTypes: [],        ingredients: [
            { name: 'riz', quantity: 500, unit: Unit.G },
            { name: 'poulet', quantity: 1000, unit: Unit.G },
            { name: 'oignon', quantity: 3, unit: Unit.PIECE },
            { name: 'tomate', quantity: 3, unit: Unit.PIECE },
            { name: 'yaourt', quantity: 200, unit: Unit.G },
            { name: 'gingembre', quantity: 30, unit: Unit.G },
            { name: 'ail', quantity: 6, unit: Unit.CLOVE },
            { name: 'curry', quantity: 2, unit: Unit.TSP },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'coriandre en poudre', quantity: 2, unit: Unit.TSP },
            { name: 'safran', quantity: 0.5, unit: Unit.TSP },
            { name: 'huile végétale', quantity: 4, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire mariner le poulet dans le yaourt avec les épices et le gingembre-ail 2h.' },
            { stepNumber: 2, instruction: 'Faire revenir les oignons dans l\'huile jusqu\'à dorés, ajouter les tomates.' },
            { stepNumber: 3, instruction: 'Ajouter le poulet mariné et cuire 30 minutes.' },
            { stepNumber: 4, instruction: 'Faire cuire le riz à moitié, le disposer sur le poulet, saupoudrer de safran.' },
            { stepNumber: 5, instruction: 'Couvrir et cuire au four 30 minutes à 160°C. Servir chaud.' },
        ],
    },

    // === RECETTES VÉGÉTARIENNES AVANCÉES ===
    {
        title: 'Risotto aux Asperges',
        slug: 'risotto-asperges',
        description: 'Risotto crémeux aux asperges fraîches',
        prepTime: 15,
        cookTime: 30,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['vegetarian', 'italian', 'healthy'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'riz', quantity: 350, unit: Unit.G },
            { name: 'asperges', quantity: 500, unit: Unit.G },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'bouillon de légumes', quantity: 1000, unit: Unit.ML },
            { name: 'vin blanc', quantity: 100, unit: Unit.ML },
            { name: 'parmesan', quantity: 60, unit: Unit.G },
            { name: 'beurre', quantity: 40, unit: Unit.G },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire les asperges à la vapeur, réserver les pointes.' },
            { stepNumber: 2, instruction: 'Mixer les tiges d\'asperges avec un peu de bouillon.' },
            { stepNumber: 3, instruction: 'Faire revenir l\'oignon dans le beurre, ajouter le riz et nacrer.' },
            { stepNumber: 4, instruction: 'Ajouter le vin, puis le bouillon et le mélange d\'asperges louche par louche.' },
            { stepNumber: 5, instruction: 'À la fin, ajouter les pointes d\'asperges, le parmesan et servir.' },
        ],
    },
    {
        title: 'Gratin de Pommes de Terre au Tofu',
        slug: 'gratin-pommes-terre-tofu',
        description: 'Gratin végétarien avec pommes de terre et tofu mariné',
        prepTime: 25,
        cookTime: 50,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['vegetarian', 'comfort_food'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'pomme de terre', quantity: 1500, unit: Unit.G },
            { name: 'tofu', quantity: 400, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'lait de coco', quantity: 400, unit: Unit.ML },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'curry', quantity: 1, unit: Unit.TSP },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 180°C. Couper les pommes de terre en rondelles fines.' },
            { stepNumber: 2, instruction: 'Faire mariner le tofu avec les épices et l\'ail 15 minutes.' },
            { stepNumber: 3, instruction: 'Faire revenir l\'oignon et le tofu mariné dans l\'huile.' },
            { stepNumber: 4, instruction: 'Disposer en couches alternées pommes de terre et tofu dans un plat.' },
            { stepNumber: 5, instruction: 'Verser le lait de coco, saler et cuire 45 minutes couvert puis 10 minutes découvert.' },
        ],
    },
    {
        title: 'Burger de Légumineuses',
        slug: 'burger-legumineuses',
        description: 'Burgers végétariens aux pois chiches et haricots rouges',
        prepTime: 30,
        cookTime: 20,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['vegetarian', 'healthy'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'pois chiches', quantity: 400, unit: Unit.G },
            { name: 'haricots rouges', quantity: 200, unit: Unit.G },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'farine', quantity: 80, unit: Unit.G },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'coriandre en poudre', quantity: 1, unit: Unit.TSP },
            { name: 'pain', quantity: 4, unit: Unit.SLICE },
            { name: 'salade', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'tomate', quantity: 2, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Égoutter et mixer grossièrement les légumineuses.' },
            { stepNumber: 2, instruction: 'Râper les carottes, émincer l\'oignon, mélanger avec les légumineuses.' },
            { stepNumber: 3, instruction: 'Ajouter farine, épices et former 4 galettes.' },
            { stepNumber: 4, instruction: 'Faire cuire au four 180°C 15 minutes de chaque côté.' },
            { stepNumber: 5, instruction: 'Servir dans le pain avec salade et tomates.' },
        ],
    },

    // === RECETTES POISSONS ===
    {
        title: 'Filet de Bar aux Légumes',
        slug: 'filet-bar-legumes',
        description: 'Filet de bar cuit au four avec légumes de saison',
        prepTime: 15,
        cookTime: 25,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['fish', 'healthy'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.PESCATARIAN],        ingredients: [
            { name: 'bar', quantity: 800, unit: Unit.G },
            { name: 'courgette', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate cerise', quantity: 300, unit: Unit.G },
            { name: 'citron', quantity: 2, unit: Unit.PIECE },
            { name: 'thym', quantity: 1, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 200°C.' },
            { stepNumber: 2, instruction: 'Disposer les filets de bar dans un plat avec les légumes coupés.' },
            { stepNumber: 3, instruction: 'Arroser d\'huile, ajouter l\'ail, le thym, le citron, saler.' },
            { stepNumber: 4, instruction: 'Cuire 20-25 minutes au four.' },
            { stepNumber: 5, instruction: 'Servir chaud avec du citron.' },
        ],
    },
    {
        title: 'Soupe de Poisson',
        slug: 'soupe-poisson',
        description: 'Soupe provençale aux poissons et fruits de mer',
        prepTime: 30,
        cookTime: 40,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['fish', 'soup', 'french'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.PESCATARIAN],        ingredients: [
            { name: 'poisson blanc', quantity: 600, unit: Unit.G },
            { name: 'crevettes', quantity: 300, unit: Unit.G },
            { name: 'moules', quantity: 500, unit: Unit.G },
            { name: 'tomate', quantity: 4, unit: Unit.PIECE },
            { name: 'fenouil', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'vin blanc', quantity: 200, unit: Unit.ML },
            { name: 'bouillon de poisson', quantity: 1000, unit: Unit.ML },
            { name: 'safran', quantity: 0.5, unit: Unit.TSP },
            { name: 'persil', quantity: 1, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir les légumes dans l\'huile 10 minutes.' },
            { stepNumber: 2, instruction: 'Ajouter le vin blanc, le bouillon et le safran, porter à ébullition.' },
            { stepNumber: 3, instruction: 'Ajouter le poisson et les fruits de mer, cuire 15 minutes.' },
            { stepNumber: 4, instruction: 'Retirer les coquilles des moules, remettre dans la soupe.' },
            { stepNumber: 5, instruction: 'Parsemer de persil et servir avec des croûtons.' },
        ],
    },
    {
        title: 'Thon à la Basquaise',
        slug: 'thon-basquaise',
        description: 'Filets de thon à la sauce basquaise aux poivrons',
        prepTime: 20,
        cookTime: 30,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['fish', 'french'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.PESCATARIAN],        ingredients: [
            { name: 'thon', quantity: 800, unit: Unit.G },
            { name: 'poivron', quantity: 4, unit: Unit.PIECE },
            { name: 'tomate', quantity: 3, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'vin blanc', quantity: 100, unit: Unit.ML },
            { name: 'bouillon de poisson', quantity: 200, unit: Unit.ML },
            { name: 'persil', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'piment', quantity: 1, unit: Unit.PIECE },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire griller les poivrons, les peler et les couper en lanières.' },
            { stepNumber: 2, instruction: 'Faire revenir l\'oignon et l\'ail, ajouter les poivrons et tomates.' },
            { stepNumber: 3, instruction: 'Ajouter le vin et le bouillon, laisser mijoter 20 minutes.' },
            { stepNumber: 4, instruction: 'Faire griller les filets de thon 3 minutes de chaque côté.' },
            { stepNumber: 5, instruction: 'Servir le thon avec la sauce basquaise et le persil.' },
        ],
    },

    // === RECETTES COMFORT FOOD ===
    {
        title: 'Hachis Parmentier',
        slug: 'hachis-parmentier',
        description: 'Hachis parmentier traditionnel à la viande hachée',
        prepTime: 30,
        cookTime: 45,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['french', 'comfort_food'],
        toolsRequired: ['oven'],
        dietTypes: [],        ingredients: [
            { name: 'pomme de terre', quantity: 1200, unit: Unit.G },
            { name: 'boeuf haché', quantity: 600, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'lait', quantity: 150, unit: Unit.ML },
            { name: 'beurre', quantity: 60, unit: Unit.G },
            { name: 'fromage râpé', quantity: 150, unit: Unit.G },
            { name: 'vin rouge', quantity: 100, unit: Unit.ML },
            { name: 'ail', quantity: 2, unit: Unit.CLOVE },
            { name: 'thym', quantity: 1, unit: Unit.TSP },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire les pommes de terre à l\'eau, les écraser avec le lait et le beurre.' },
            { stepNumber: 2, instruction: 'Faire revenir la viande avec oignon et ail, ajouter le vin et le thym.' },
            { stepNumber: 3, instruction: 'Dans un plat, disposer la viande puis la purée de pommes de terre.' },
            { stepNumber: 4, instruction: 'Parsemer de fromage râpé et cuire au four 35 minutes à 180°C.' },
            { stepNumber: 5, instruction: 'Servir très chaud.' },
        ],
    },
    {
        title: 'Chili Sin Carne',
        slug: 'chili-sin-carne',
        description: 'Chili végétarien aux haricots et légumes',
        prepTime: 20,
        cookTime: 45,
        difficulty: Difficulty.EASY,
        servings: 6,
        tags: ['vegetarian', 'comfort_food', 'spicy'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'haricots rouges', quantity: 600, unit: Unit.G },
            { name: 'haricots noirs', quantity: 400, unit: Unit.G },
            { name: 'tomate concassée', quantity: 600, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'poivron', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'paprika', quantity: 1, unit: Unit.TSP },
            { name: 'piment', quantity: 1, unit: Unit.PIECE },
            { name: 'cacao', quantity: 1, unit: Unit.TBSP },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir les oignons et l\'ail dans l\'huile.' },
            { stepNumber: 2, instruction: 'Ajouter les poivrons coupés en dés, faire revenir 5 minutes.' },
            { stepNumber: 3, instruction: 'Ajouter les épices et le cacao, remuer 1 minute.' },
            { stepNumber: 4, instruction: 'Ajouter les tomates, les haricots égouttés, couvrir et mijoter 35 minutes.' },
            { stepNumber: 5, instruction: 'Servir avec du riz et de la crème aigre (optionnel).' },
        ],
    },
    {
        title: 'Macaroni au Fromage',
        slug: 'macaroni-fromage',
        description: 'Mac and cheese crémeux et réconfortant',
        prepTime: 15,
        cookTime: 30,
        difficulty: Difficulty.EASY,
        servings: 6,
        tags: ['comfort_food', 'vegetarian'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'macaroni', quantity: 500, unit: Unit.G },
            { name: 'fromage râpé', quantity: 300, unit: Unit.G },
            { name: 'beurre', quantity: 60, unit: Unit.G },
            { name: 'farine', quantity: 50, unit: Unit.G },
            { name: 'lait', quantity: 600, unit: Unit.ML },
            { name: 'moutarde', quantity: 1, unit: Unit.TSP },
            { name: 'paprika', quantity: 1, unit: Unit.TSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire les macaronis selon les instructions.' },
            { stepNumber: 2, instruction: 'Faire fondre le beurre, ajouter la farine et remuer 2 minutes.' },
            { stepNumber: 3, instruction: 'Ajouter le lait progressivement en fouettant jusqu\'à épaississement.' },
            { stepNumber: 4, instruction: 'Ajouter le fromage râpé, la moutarde et le paprika, mélanger.' },
            { stepNumber: 5, instruction: 'Mélanger avec les pâtes, verser dans un plat et gratiner au four 15 minutes.' },
        ],
    },
    {
        title: 'Sauce Bolognaise Maison',
        slug: 'sauce-bolognaise-maison',
        description: 'Sauce bolognaise traditionnelle à mijoter longuement',
        prepTime: 20,
        cookTime: 180,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['italian', 'comfort_food'],
        toolsRequired: ['casserole'],
        dietTypes: [],        ingredients: [
            { name: 'boeuf haché', quantity: 750, unit: Unit.G },
            { name: 'tomate concassée', quantity: 750, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'céleri', quantity: 2, unit: Unit.PIECE },
            { name: 'lardons', quantity: 100, unit: Unit.G },
            { name: 'vin rouge', quantity: 200, unit: Unit.ML },
            { name: 'bouillon de légumes', quantity: 300, unit: Unit.ML },
            { name: 'lait', quantity: 100, unit: Unit.ML },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'basilic', quantity: 1, unit: Unit.BUNCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir les lardons, puis les légumes finement coupés dans l\'huile.' },
            { stepNumber: 2, instruction: 'Ajouter la viande et faire revenir jusqu\'à cuisson complète.' },
            { stepNumber: 3, instruction: 'Verser le vin et laisser réduire de moitié.' },
            { stepNumber: 4, instruction: 'Ajouter les tomates, le bouillon et le lait. Laisser mijoter 2h30 à feu très doux.' },
            { stepNumber: 5, instruction: 'Ajouter le basilic en fin de cuisson. Servir avec des pâtes fraîches.' },
        ],
    },

    // === RECETTES DESSERTS ===
    {
        title: 'Cheesecake aux Fruits Rouges',
        slug: 'cheesecake-fruits-rouges',
        description: 'Cheesecake crémeux avec coulis de fruits rouges',
        prepTime: 30,
        cookTime: 60,
        difficulty: Difficulty.HARD,
        servings: 10,
        isAdaptable: false,
        tags: ['dessert', 'classic'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'biscuits à la cuillère', quantity: 30, unit: Unit.PIECE },
            { name: 'beurre', quantity: 100, unit: Unit.G },
            { name: 'mascarpone', quantity: 600, unit: Unit.G },
            { name: 'sucre', quantity: 150, unit: Unit.G },
            { name: 'oeuf', quantity: 3, unit: Unit.PIECE },
            { name: 'crème fraîche', quantity: 200, unit: Unit.ML },
            { name: 'fraise', quantity: 200, unit: Unit.G },
            { name: 'framboise', quantity: 200, unit: Unit.G },
            { name: 'sucre glace', quantity: 50, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Écraser les biscuits et mélanger avec le beurre fondu, tasser dans un moule.' },
            { stepNumber: 2, instruction: 'Battre le fromage à la crème avec le sucre jusqu\'à lisse.' },
            { stepNumber: 3, instruction: 'Ajouter les œufs un par un, puis la crème fraîche.' },
            { stepNumber: 4, instruction: 'Verser sur le fond de biscuits et cuire au bain-marie 50 minutes à 160°C.' },
            { stepNumber: 5, instruction: 'Laisser refroidir, mixer les fruits rouges avec le sucre glace pour le coulis.' },
        ],
    },
    {
        title: 'Mousse au Chocolat',
        slug: 'mousse-chocolat',
        description: 'Mousse au chocolat noir légère et aérienne',
        prepTime: 20,
        cookTime: 0,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['dessert', 'quick'],
        toolsRequired: [],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'chocolat noir', quantity: 200, unit: Unit.G },
            { name: 'oeuf', quantity: 4, unit: Unit.PIECE },
            { name: 'sucre', quantity: 60, unit: Unit.G },
            { name: 'beurre', quantity: 30, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire fondre le chocolat avec le beurre au bain-marie.' },
            { stepNumber: 2, instruction: 'Séparer les blancs des jaunes d\'œufs.' },
            { stepNumber: 3, instruction: 'Mélanger les jaunes avec le chocolat fondu refroidi.' },
            { stepNumber: 4, instruction: 'Monter les blancs en neige avec le sucre et les incorporer délicatement.' },
            { stepNumber: 5, instruction: 'Réserver au frais 4 heures minimum avant de servir.' },
        ],
    },
    {
        title: 'Tarte aux Pommes',
        slug: 'tarte-pommes',
        description: 'Tarte aux pommes traditionnelle française',
        prepTime: 30,
        cookTime: 45,
        difficulty: Difficulty.MEDIUM,
        servings: 8,
        isAdaptable: false,
        tags: ['dessert', 'french'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'pâte brisée', quantity: 1, unit: Unit.PIECE },
            { name: 'pomme', quantity: 8, unit: Unit.PIECE },
            { name: 'sucre', quantity: 80, unit: Unit.G },
            { name: 'beurre', quantity: 40, unit: Unit.G },
            { name: 'cannelle', quantity: 1, unit: Unit.TSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 180°C.' },
            { stepNumber: 2, instruction: 'Étaler la pâte dans un moule à tarte et piquer le fond.' },
            { stepNumber: 3, instruction: 'Éplucher et couper les pommes en quartiers, les disposer en rosace.' },
            { stepNumber: 4, instruction: 'Saupoudrer de sucre et de cannelle, parsemer de beurre en petits morceaux.' },
            { stepNumber: 5, instruction: 'Cuire 40-45 minutes jusqu\'à ce que les pommes soient tendres.' },
        ],
    },
    {
        title: 'Crème Brûlée',
        slug: 'creme-brulee',
        description: 'Crème brûlée à la vanille, dessert français classique',
        prepTime: 20,
        cookTime: 40,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        isAdaptable: false,
        tags: ['dessert', 'french'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'crème fraîche', quantity: 500, unit: Unit.ML },
            { name: 'lait', quantity: 200, unit: Unit.ML },
            { name: 'jaune d\'oeuf', quantity: 6, unit: Unit.PIECE },
            { name: 'sucre', quantity: 80, unit: Unit.G },
            { name: 'vanille', quantity: 1, unit: Unit.PIECE },
            { name: 'sucre pour caraméliser', quantity: 60, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 100°C. Faire chauffer la crème avec le lait et la gousse de vanille fendue.' },
            { stepNumber: 2, instruction: 'Battre les jaunes avec le sucre jusqu\'à blanchiment.' },
            { stepNumber: 3, instruction: 'Verser la crème chaude sur les jaunes en remuant, retirer la vanille.' },
            { stepNumber: 4, instruction: 'Verser dans des ramequins et cuire au bain-marie 30 minutes.' },
            { stepNumber: 5, instruction: 'Laisser refroidir, saupoudrer de sucre et caraméliser au chalumeau avant de servir.' },
        ],
    },

    // === RECETTES PETIT-DÉJEUNER ===
    {
        title: 'Oeufs Bénédictine',
        slug: 'oeufs-benedictine',
        description: 'Oeufs pochés, bacon, muffin anglais et sauce hollandaise',
        prepTime: 30,
        cookTime: 15,
        difficulty: Difficulty.HARD,
        servings: 4,
        tags: ['breakfast', 'classic'],
        toolsRequired: ['casserole'],
        dietTypes: [],        ingredients: [
            { name: 'oeuf', quantity: 4, unit: Unit.PIECE },
            { name: 'bacon', quantity: 8, unit: Unit.SLICE },
            { name: 'muffin anglais', quantity: 4, unit: Unit.PIECE },
            { name: 'beurre', quantity: 150, unit: Unit.G },
            { name: 'oeuf', quantity: 3, unit: Unit.PIECE },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'vinaigre', quantity: 2, unit: Unit.TBSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire griller le bacon et toaster les muffins.' },
            { stepNumber: 2, instruction: 'Faire la sauce hollandaise : faire fondre le beurre, battre les jaunes avec le jus de citron au bain-marie, ajouter le beurre en fouettant.' },
            { stepNumber: 3, instruction: 'Pocher les œufs dans l\'eau bouillante avec du vinaigre 3-4 minutes.' },
            { stepNumber: 4, instruction: 'Disposer bacon sur les muffins, puis les œufs pochés.' },
            { stepNumber: 5, instruction: 'Napper de sauce hollandaise et servir immédiatement.' },
        ],
    },
    {
        title: 'Granola Maison',
        slug: 'granola-maison',
        description: 'Granola croustillant aux fruits secs et noix',
        prepTime: 15,
        cookTime: 30,
        difficulty: Difficulty.EASY,
        servings: 12,
        tags: ['breakfast', 'healthy'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'flocons d\'avoine', quantity: 500, unit: Unit.G },
            { name: 'noix', quantity: 200, unit: Unit.G },
            { name: 'amandes', quantity: 150, unit: Unit.G },
            { name: 'miel', quantity: 100, unit: Unit.ML },
            { name: 'huile de coco', quantity: 80, unit: Unit.ML },
            { name: 'raisin sec', quantity: 150, unit: Unit.G },
            { name: 'cannelle', quantity: 1, unit: Unit.TSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 150°C.' },
            { stepNumber: 2, instruction: 'Mélanger les flocons d\'avoine, noix et amandes avec le miel et l\'huile.' },
            { stepNumber: 3, instruction: 'Ajouter la cannelle et étaler sur une plaque.' },
            { stepNumber: 4, instruction: 'Cuire 25-30 minutes en remuant toutes les 10 minutes.' },
            { stepNumber: 5, instruction: 'Ajouter les raisins secs après cuisson. Laisser refroidir et conserver dans un bocal.' },
        ],
    },
    {
        title: 'Smoothie Bowl',
        slug: 'smoothie-bowl',
        description: 'Bowl de smoothie aux fruits et toppings',
        prepTime: 10,
        cookTime: 0,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['breakfast', 'healthy', 'quick'],
        toolsRequired: [],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'banane', quantity: 2, unit: Unit.PIECE },
            { name: 'myrtille', quantity: 100, unit: Unit.G },
            { name: 'fraise', quantity: 100, unit: Unit.G },
            { name: 'yaourt', quantity: 200, unit: Unit.G },
            { name: 'miel', quantity: 2, unit: Unit.TBSP },
            { name: 'flocons d\'avoine', quantity: 60, unit: Unit.G },
            { name: 'noix de coco râpée', quantity: 20, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Mixer la banane, les fruits rouges, le yaourt et le miel.' },
            { stepNumber: 2, instruction: 'Verser dans des bols.' },
            { stepNumber: 3, instruction: 'Garnir avec le granola et la noix de coco.' },
            { stepNumber: 4, instruction: 'Servir immédiatement.' },
        ],
    },

    // === RECETTES VÉGÉTARIENNES COMPLÈTES ===
    {
        title: 'Dahl de Lentilles',
        slug: 'dahl-lentilles',
        description: 'Dahl indien aux lentilles corail et épices',
        prepTime: 10,
        cookTime: 30,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['vegetarian', 'indian', 'healthy'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'lentilles corail', quantity: 400, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'gingembre', quantity: 20, unit: Unit.G },
            { name: 'curry', quantity: 2, unit: Unit.TSP },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
            { name: 'coriandre', quantity: 1, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'bouillon de légumes', quantity: 800, unit: Unit.ML },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir l\'oignon, l\'ail et le gingembre dans l\'huile.' },
            { stepNumber: 2, instruction: 'Ajouter les épices et remuer 1 minute.' },
            { stepNumber: 3, instruction: 'Ajouter les lentilles rincées, les tomates et le bouillon.' },
            { stepNumber: 4, instruction: 'Porter à ébullition puis laisser mijoter 25 minutes.' },
            { stepNumber: 5, instruction: 'Ajouter la coriandre ciselée. Servir avec du riz.' },
        ],
    },
    {
        title: 'Quiche aux Épinards',
        slug: 'quiche-epinards',
        description: 'Quiche végétarienne aux épinards et fromage de chèvre',
        prepTime: 20,
        cookTime: 40,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        isAdaptable: false,
        tags: ['vegetarian', 'french'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],        ingredients: [
            { name: 'pâte brisée', quantity: 1, unit: Unit.PIECE },
            { name: 'épinard', quantity: 500, unit: Unit.G },
            { name: 'fromage de chèvre sec', quantity: 200, unit: Unit.G },
            { name: 'oeuf', quantity: 3, unit: Unit.PIECE },
            { name: 'crème fraîche', quantity: 200, unit: Unit.ML },
            { name: 'noix de muscade', quantity: 0.5, unit: Unit.TSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 180°C. Étaler la pâte dans un moule et piquer.' },
            { stepNumber: 2, instruction: 'Faire blanchir les épinards, les égoutter et les hacher.' },
            { stepNumber: 3, instruction: 'Battre les œufs avec la crème, la muscade et le sel.' },
            { stepNumber: 4, instruction: 'Disposer les épinards et le fromage sur la pâte, verser l\'appareil.' },
            { stepNumber: 5, instruction: 'Cuire 35-40 minutes jusqu\'à doré.' },
        ],
    },
    {
        title: 'Buddha Bowl',
        slug: 'buddha-bowl',
        description: 'Bowl équilibré avec légumes, céréales et légumineuses',
        prepTime: 20,
        cookTime: 20,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['vegetarian', 'healthy'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],        ingredients: [
            { name: 'quinoa', quantity: 300, unit: Unit.G },
            { name: 'patate douce', quantity: 600, unit: Unit.G },
            { name: 'brocoli', quantity: 400, unit: Unit.G },
            { name: 'pois chiches', quantity: 400, unit: Unit.G },
            { name: 'avocat', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate cerise', quantity: 200, unit: Unit.G },
            { name: 'citron', quantity: 2, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire le quinoa selon les instructions.' },
            { stepNumber: 2, instruction: 'Couper la patate douce en dés et cuire au four 180°C 20 minutes.' },
            { stepNumber: 3, instruction: 'Faire cuire le brocoli à la vapeur et épicer les pois chiches avec le cumin.' },
            { stepNumber: 4, instruction: 'Disposer le quinoa dans des bols, ajouter tous les légumes et l\'avocat.' },
            { stepNumber: 5, instruction: 'Arroser d\'huile d\'olive et de jus de citron.' },
        ],
    },
];

