volumes:
  reverse-proxy:
  muscu-data:
  jow-postgres-data:

services:
  reverse-proxy:
    restart: always
    image: traefik:v2.0
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - ~/pi/services.toml:/etc/traefik/services.toml
    - ~/pi/traefik.toml:/etc/traefik/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.http.routers.api.rule=Host(`traefik.chocot.be`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.entrypoints=http"
    - "traefik.http.routers.api.middlewares=auth"
    - "traefik.http.middlewares.auth.basicauth.users=pi:$$apr1$$5uYcSiA9$$pf3V/rEtqAG1I0ZLHRnT40"

  muscu-app-back:
    build: ~/fittrack/backend
    container_name: muscu-app-back
    ports:
      - "3001:3001"  # utile pour test local, mais Traefik n'en a pas besoin
    volumes:
      - ~/muscu-data:/app/data  # accès au volume partagé
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.muscu.rule=Host(`apimuscu.chocot.be`)"
      - "traefik.http.routers.muscu.entrypoints=http"  # ou 'websecure' si tu a>
      - "traefik.http.services.muscu.loadbalancer.server.port=3001"
      - "traefik.http.routers.muscu.service=muscu"
    restart: none

  muscu-front:
    build: ~/fittrack
    container_name: muscu-front
    ports:
      - "9999:80"
    volumes:
      - ~/muscu-data:/app/data  # accès au volume partagé
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.muscu-front.rule=Host(`muscu.chocot.be`)"
      - "traefik.http.routers.muscu-front.entrypoints=http"
      - "traefik.http.services.muscu-front.loadbalancer.server.port=80"
    restart: none

  salary:
    build: ~/salary-tracking
    container_name: salary
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.salary.rule=Host(`salaire.chocot.be`)"
      - "traefik.http.routers.salary.entrypoints=http"
      - "traefik.http.services.salary.loadbalancer.server.port=3000"
      - "traefik.http.routers.salary.service=salary"
    restart: none


#  apache:
#    image: php:8.1-apache
#    container_name: apache
#    restart: always
#    volumes:
#      - ~/cv:/var/www/html
#    ports:
#      - 8080:80
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.apache.rule=Host(`chocot.be`)"
#      - "traefik.http.routers.apache.entrypoints=http"
#      - "traefik.http.services.apache.loadbalancer.server.port=80"


  cv-front:
    build: ~/folio-flex-project   # répertoire qui contient le Dockerfile et le projet Vite
    container_name: cv-front
    restart: always
    # ports optionnels pour test local, pas requis pour Traefik
    # - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv.rule=Host(`chocot.be`)"
      - "traefik.http.routers.cv.entrypoints=http"
      - "traefik.http.services.cv.loadbalancer.server.port=80"
      - "traefik.http.routers.cv.service=cv"

  # FoodTrack - Base de données PostgreSQL
  jow-postgres:
    image: postgres:16-alpine
    container_name: jow-postgres
    restart: always
    environment:
      POSTGRES_USER: jow_user
      POSTGRES_PASSWORD: ${JOW_DB_PASSWORD:-jow_production_password_change_me}
      POSTGRES_DB: jow_db
    volumes:
      - jow-postgres-data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jow_user -d jow_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FoodTrack - Backend API
  jow-backend:
    build: ~/foodtrack/backend
    container_name: jow-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://jow_user:${JOW_DB_PASSWORD:-jow_production_password_change_me}@jow-postgres:5432/jow_db?schema=public
      JWT_SECRET: ${JOW_JWT_SECRET:-change-this-super-secret-jwt-key-in-production}
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: https://food.chocot.be
      # Email configuration
      SMTP_HOST: ${JOW_SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${JOW_SMTP_PORT:-587}
      SMTP_SECURE: ${JOW_SMTP_SECURE:-false}
      SMTP_USER: ${JOW_SMTP_USER}
      SMTP_PASS: ${JOW_SMTP_PASS}
      SMTP_FROM: ${JOW_SMTP_FROM:-noreply@jow.chocot.be}
      ADMIN_EMAIL: ${JOW_ADMIN_EMAIL:-benoit.chocot@gmail.com}
      FRONTEND_URL: https://food.chocot.be
    volumes:
      - ~/jow-uploads:/app/uploads
    depends_on:
      jow-postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jow-api.rule=Host(`apijow.chocot.be`)"
      - "traefik.http.routers.jow-api.entrypoints=http"
      - "traefik.http.services.jow-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.jow-api.service=jow-api"

  # FoodTrack - Frontend
  jow-frontend:
    build: ~/foodtrack/frontend
    container_name: jow-frontend
    restart: always
    environment:
      NUXT_PUBLIC_API_BASE: https://apifood.chocot.be
    depends_on:
      - jow-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jow.rule=Host(`food.chocot.be`)"
      - "traefik.http.routers.jow.entrypoints=http"
      - "traefik.http.services.jow.loadbalancer.server.port=3000"
      - "traefik.http.routers.jow.service=jow"


#  wireguard:
#    image: lscr.io/linuxserver/wireguard
#    container_name: wireguard
#    cap_add:
#      - NET_ADMIN
#    volumes:
#      - /home/wireguard:/config
#      - /home/lib/modules:/lib/modules
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Paris
#    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
#    restart: always

#  rails:                                                                                                                     #    build: ./ticketing
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0>#    volumes:
#      - ".:/app"
#      - "./ticketing/db:/app/db"
#    ports:
#      - "3000:3000"
#    environment:
#      - DATABASE_URL=sqlite3:///app/db/production.sqlite3
#      - SECRET_KEY_BASE=84a845b75588afd910ecfc3bd297b778070af6288bccdf21c0baed698968de09c8b8341fad609001f76397d3a9545cda660f>#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.rails.loadbalancer.server.port=3000"
#      - "traefik.http.routers.rails.rule=Host(`ticket.chocot.be`)"
#      - "traefik.http.routers.rails.service=rails"

#  prowlarr:
#    image: lscr.io/linuxserver/prowlarr:latest
#    container_name: prowlarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#    volumes:
#      - /home/prowlarr/data:/config
#    restart: always
#    network_mode: "service:wireguard"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
#      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.chocot.be`)"
#      - "traefik.http.routers.prowlarr.service=prowlarr"
#      - "traefik.http.routers.prowlarr.entrypoints=http"



#  flaresolverr:
 # DockerHub mirror flaresolverr/flaresolverr:latest
# # image: ghcr.io/flaresolverr/flaresolverr:latest
#    image: alexfozor/flaresolverr:pr-1300-experimental
#    container_name: flaresolverr
#    network_mode: "service:wireguard"
#    environment:
#      - LOG_LEVEL=${LOG_LEVEL:-info}
#      - LOG_HTML=${LOG_HTML:-false}
#      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
#      - TZ=Europe/London
#    restart: always
#    volumes:
#      - /home/flaresolverr_data:/app/data
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.flare.loadbalancer.server.port=8191"
#      - "traefik.http.routers.flare.rule=Host(`flare.chocot.be`)"
#      - "traefik.http.routers.flare.service=flare"
#      - "traefik.http.routers.flare.entrypoints=http"

#  jellyfin:
#    image: jellyfin/jellyfin:latest
#    container_name: jellyfin
#    user: 1000:1000
#    volumes:
#      - /home/jelly/config:/config
#      - /home/jelly/cache:/cache
#      - type: bind
#        source: /home/videos
#        target: /media
#        read_only: false
#    ports:
#    - 8096:8096
#    restart: always
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.jelly.loadbalancer.server.port=8096"
#      - "traefik.http.routers.jelly.rule=Host(`jelly.chocot.be`)"
#      - "traefik.http.routers.jelly.service=jelly"
#

#  transmission:
#    image: lscr.io/linuxserver/transmission:latest
#    container_name: transmission
#    user: "1000:1000"
#    network_mode: "service:wireguard"
#    environment:
#    - PUID=1000
#    - PGID=1000
#    - TZ=Europe/Paris
#    - USER=bonoit
#    - PASS=Benoit45+
#    volumes:
#    - /home/transmission/config/:/config
#    - /home/transmission/downloads:/downloads
#    - /home/videos/tv-sonarr:/tv
#    - /home/books:/books
#    restart: always
#    labels:
#    - "traefik.enable=true"
#    - "traefik.http.services.torrent.loadbalancer.server.port=9091"
#    - "traefik.http.routers.torrent.rule=Host(`torrent.chocot.be`)"
#    - "traefik.http.routers.torrent.service=torrent"
#    - "traefik.http.routers.torrent.entrypoints=http"

#  sonarr:
#    image: lscr.io/linuxserver/sonarr:latest
#    container_name: sonarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#    network_mode: "service:wireguard"
#    volumes:
#      - /home/sonarr/config:/config
#      - /home/videos:/tv #optional
#      - /home/transmission/downloads:/downloads #optional
#    restart: always
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
#      - "traefik.http.routers.sonarr.rule=Host(`sonarr.chocot.be`)"
#      - "traefik.http.routers.sonarr.service=sonarr"
#      - "traefik.http.routers.sonarr.entrypoints=http"
